server:
  port: 8888
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/library?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: rmsoft
      password: rmsoft
  config:
    activate:
      on-profile: prod
jwt:
  issuer: rmsoft
  secret-key: library
mybatis:
  type-aliases-package: com.rmsoft.library.domain
  configuration:
    map-underscore-to-camel-case: true