server:
  port: 5000
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:ebdb}
      #      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: ${RDS_USERNAME:suwanrmsoft}
      password: ${RDS_PASSWORD:suwanrmsoft}
jwt:
  issuer: rmsoft
  secret-key: library
mybatis:
  type-aliases-package: com.rmsoft.library.domain
  configuration:
    map-underscore-to-camel-case: true

